var abi = /* abi generated by the compiler */

var ZombieFeedingContract = web3.eth.contract(abi)
var contractAddress = /* our contract address on Ethereum after deploying */
var ZombieFeeding = ZombieFeedingContract.at(contractAddress);

// Assuming we have our zombie's ID and the kitty ID we want to attack
let zombieId = 1;
let kittyId = 1;
Quarkus
Released in 2019
Open source project initiated by RedHat
Cloud-native framework
Facilitates the build of modern java applications:
	Rapid start-up times
	Higher throughput
	Low-memory footprint
Rich integrations with wide range of Java libraries.
let apiUrl = "https://api.cryptokitties.co/kitties/" + kittyId
$.get(apiUrl, function(data) {
	let imgUrl = data.image_url
	// do something to display the image
})

$(".kittyImage").click(function(e) {
	ZombieFeeding.feedOnKitty(zombieId, kittyId);
})

ZombieFactory.NewZombie(function(error, result) {
	if (error) return
	
	generateZombie(result.zombieId, result.name, result.dna)
})